kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: example-pipeline
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'Namespace where the application is running'
      name: NAMESPACE
      default: "default"
      type: string
    - description: 'Expected output'
      name: EXPECTED_OUTPUT
      default: "Hello World!"
      type: string
  tasks:
    - name: task-1
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
        - name: SNAPSHOT
        results:
        - name: TEST_OUTPUT
          description: Test output
        steps:
        - image: registry.redhat.io/openshift4/ose-cli:latest
          env:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
          - name: MY_SECRET
            valueFrom:
              secretKeyRef:
                name: "a"
                key: "b"
          - name: MY_SECRET_2
            valueFrom:
              secretKeyRef:
                name: "foo"
                key: "bar"
          script: |
            dnf -y install jq python3-pip
            pip3 install pytest
            echo -e "Example test task for the Snapshot:\n ${SNAPSHOT}"
            env
            ls -la
            echo ${SNAPSHOT} | jq .
            // pytest -v
            // Run custom tests for the given Snapshot here
            // After the tests finish, record the overall result in the RESULT variable
            RESULT="SUCCESS"

            // Output the standardized TEST_OUTPUT result in JSON form
            TEST_OUTPUT=$(jq -rc --arg date $(date +%s) --arg RESULT "${RESULT}" --null-input \
              '{result: $RESULT, timestamp: $date, failures: 0, successes: 1, warnings: 0}')
            echo "${TEST_OUTPUT}"
            echo -n "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)
